terraformState: cloud  # local, cloud
clustersProjectId: "my-project"
governanceProjectId: "my-project" 
region: "us-east1" # Region for resources aside from GKE clusters
enableWindowsNodepool: false 
enablePreemptibleNodepool: false # Enforced on Linux Node pools only
privateEndpoint: false
releaseChannel: REGULAR
defaultNodepoolOS: cos
initialNodeCount: 1
maxNodeCount: 10
minNodeCount: 3
configSync: false
policyController: false
multiClusterGateway: true
anthosServiceMesh: true
tfModuleRepo: "github.com/GoogleCloudPlatform/gke-poc-toolkit//terraform/modules/"
tfModuleBranch: "main"
sendAnalytics: true
vpcConfig:
  vpcName: "argo-demo"
  vpcType: "standalone" # standalone, shared 
  vpcProjectId: "my-host-project" # Required if you are using a sharedVPC
  podCIDRName: "mypodcidr"
  svcCIDRName: "mysvccidr"
  authCIDR: "0.0.0.0/0" # only needed if enabling private endpoints for clusters
clustersConfig:  # a list of one or more clusters, each with their own config 
- clusterName: "mccp-central-01"
  machineType: "e2-standard-4"
  region: "us-central1" 
  zone: "us-central1-b"  
  subnetName: "us-central1"